### PR TITLE
Support version with get method and delete method.

### PR DESCRIPTION
**Pull request by itumo-arigatone**
https://github.com/adorechic/rcredstash/issues/15
Hello.I saw this issue and created it so that the get and delete methods can specify version.
Then I created a process to display key and version together in the list method with the -v option.

### CODE REVIEW

**Review by adorechic — COMMENTED** [review]
Thanks!

Codes looks good. Please add specs.

**Comment by itumo-arigatone** [comment]
The process of setting parameters has been divided into functions. Then I wrote an spec to verify the parameters set by that function.

**Review by adorechic — APPROVED** [review]
LGTM

**Comment by adorechic** [comment]
Thanks, now released https://rubygems.org/gems/rcredstash/versions/1.1.0

**Pull request merged**
